import { test } from '@playwright/test';

test('test', async ({ page }) => {
// login Page
  await page.goto('https://testportaludc.aurionpro.com/login');
  await page.getByRole('button', { name: 'Login with FIS' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).fill('pramod.more');
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Sanvi@123456');
  await page.getByRole('radio', { name: 'Yes, this is my computer or' }).check();
  await page.getByRole('button', { name: 'Sign in' }).click();
  // start page
  await page.getByRole('link', { name: 'Quotes & Applications Quotes' }).click();
  //Dashboard Page
  await page.getByRole('button', { name: ' + Create Standard Quote' }).click();
  await page.getByRole('link', { name: 'Credit Sale Agreement' }).click();
  // Create Quote Page
  await page.locator('#pn_id_394').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByText('CSA-B-Assigned').click();
  await page.locator('#pn_id_397').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'MYUDC-B-CSA-Assigned MV' }).click();
  await page.locator('text').filter({ hasText: 'Originator Reference' }).locator('#text').click();
  await page.locator('text').filter({ hasText: 'Originator Reference' }).locator('#text').fill('test');
  await page.locator('input[name="assetTypeDD"]').click();
  await page.getByRole('searchbox').click();
  await page.getByRole('searchbox').fill('tipp');
  await page.getByRole('option', { name: 'Tipper Truck / Truck / Motor' }).click();
  await page.locator('#pn_id_411').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'New' }).click();
  await page.getByRole('button', { name: 'Asset, Insurance & Trade-in' }).click();
  await page.locator('.cursor-pointer.fa-pen-to-square').click();
  await page.getByRole('textbox', { name: 'Asset Value* Sum Insured Net' }).click();
  await page.locator('text').filter({ hasText: 'Make' }).locator('#text').click();
  await page.locator('text').filter({ hasText: 'Make' }).locator('#text').fill('a');
  await page.locator('text').filter({ hasText: 'Model' }).locator('#text').click();
  await page.locator('text').filter({ hasText: 'Model' }).locator('#text').fill('ad');
  await page.locator('text').filter({ hasText: 'Variant' }).locator('#text').click();
  await page.locator('text').filter({ hasText: 'Variant' }).locator('#text').fill('adg');
  await page.locator('text').filter({ hasText: 'Rego No.' }).locator('#text').click();
  await page.locator('text').filter({ hasText: 'Rego No.' }).locator('#text').fill('adsf');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.locator('app-dealer-finance').getByRole('spinbutton').click();
  await page.locator('app-dealer-finance').getByRole('spinbutton').press('ArrowRight');
  await page.locator('input[name="firstPaymentDate"]').click();
  await page.getByText('30', { exact: true }).click();
  await page.getByRole('button', { name: 'Calculate' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  // Personal Details Page
  await page.goto('https://testportaludc.aurionpro.com/dealer/standard-quote/create/5263');
  await page.getByRole('button', { name: ' Add Borrowers / Guarantors' }).click();
  await page.locator('.p-radiobutton-box').first().click();
  await page.locator('text').filter({ hasText: 'First Name' }).locator('#text').click();
  await page.locator('text').filter({ hasText: 'First Name' }).locator('#text').fill('QWER');
  await page.locator('text').filter({ hasText: 'Last Name' }).locator('#text').click();
  await page.locator('text').filter({ hasText: 'Last Name' }).locator('#text').fill('ABCD');
  await page.locator('input[name="dateOfBirth"]').click();
  await page.getByText('19', { exact: true }).click();
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByRole('button', { name: ' Add New Customer' }).click();
  await page.getByRole('textbox', { name: 'Trading Name* GST Number Time' }).click();
  await page.getByRole('textbox', { name: 'Trading Name* GST Number Time' }).fill('Treaser');
  await page.locator('#pn_id_795').getByRole('combobox').click();
  await page.getByText('Plant Nurseries').click();
  await page.locator('text').filter({ hasText: 'Time in Business' }).locator('#text').click();
  await page.locator('text').filter({ hasText: 'Time in Business' }).locator('#text').fill('1');
  await page.locator('#text').nth(3).click();
  await page.locator('#text').nth(3).fill('1');
  await page.locator('#pn_id_759').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'Mr', exact: true }).click();
  await page.locator('#pn_id_766').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'Male', exact: true }).click();
  await page.locator('#pn_id_770').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'Married', exact: true }).click();
  await page.locator('#pn_id_773 > .p-dropdown-trigger').click();
  await page.getByRole('option', { name: '0' }).click();
  await page.locator('#pn_id_775 > .p-dropdown-trigger').click();
  await page.getByText('+61').click();
  await page.getByRole('textbox', { name: 'Area code' }).click();
  await page.getByRole('textbox', { name: 'Area code' }).fill('12');
  await page.getByRole('textbox', { name: 'Phone number' }).click();
  await page.getByRole('textbox', { name: 'Phone number' }).fill('123456');
  await page.locator('.p-inputtext.p-component.p-element.ng-untouched.ng-pristine.ng-invalid').click();
  await page.locator('.p-inputtext.p-component.p-element.ng-untouched.ng-pristine.ng-invalid').fill('test@gmail.com');
  await page.locator('#pn_id_778 > .p-dropdown-trigger').click();
  await page.getByRole('option', { name: 'None' }).click();
  await page.locator('#pn_id_784 > .p-dropdown-trigger').click();
  await page.getByRole('option', { name: 'Yes' }).click();
  await page.locator('#pn_id_786 > .p-dropdown-trigger').click();
  await page.getByRole('option', { name: 'New Zealand' }).click();
  await page.locator('#pn_id_788 > .p-dropdown-trigger').click();
  await page.getByRole('option', { name: 'New Zealand' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('input[name="physicalSearchValue"]').click();
  await page.locator('input[name="physicalSearchValue"]').fill('auc');
  await page.getByRole('option', { name: '1 Auckland Road, St Heliers,' }).click();
  await page.locator('#pn_id_810').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'Boarding' }).click();
  await page.getByRole('textbox', { name: 'Time at Address* Building' }).click();
  await page.getByRole('textbox', { name: 'Time at Address* Building' }).fill('1');
  await page.locator('#text').nth(1).click();
  await page.getByRole('textbox', { name: 'Time at Address* Building' }).fill('11');
  await page.locator('#text').nth(1).fill('1');
  await page.locator('#text').nth(1).click();
  await page.locator('p-radiobutton:nth-child(2) > .p-radiobutton > .p-radiobutton-box').click();
  await page.locator('input[name="postalSearchValue"]').click();
  await page.locator('input[name="postalSearchValue"]').fill('auck');
  await page.getByText('2 Auckland Road, St Heliers,').click();
  await page.locator('input[name="registerSearchValue"]').click();
  await page.locator('input[name="registerSearchValue"]').fill('auck');
  await page.getByText('3 Auckland Road, St Heliers,').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('textbox', { name: 'Employer Name*', exact: true }).click();
  await page.getByRole('textbox', { name: 'Employer Name*', exact: true }).fill('ACCRR');
  await page.locator('#pn_id_932').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'Accountant' }).click();
  await page.locator('#pn_id_935').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByText('Full time employed').click();
  await page.getByRole('textbox', { name: 'Time with Current Employer*' }).click();
  await page.getByRole('textbox', { name: 'Time with Current Employer*' }).fill('0');
  await page.locator('#text').nth(1).click();
  await page.locator('#text').nth(1).fill('9');
  await page.locator('text').filter({ hasText: 'Employer Name' }).locator('#text').click();
  await page.locator('text').filter({ hasText: 'Employer Name' }).locator('#text').fill('AVVCC');
  await page.locator('#pn_id_941').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.locator('#pn_id_944').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.locator('text').filter({ hasText: 'Time with Previous Employer' }).locator('#text').click();
  await page.locator('text').filter({ hasText: 'Time with Previous Employer' }).locator('#text').fill('1');
  await page.locator('#text').nth(4).click();
  await page.locator('#text').nth(4).fill('1');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('.p-radiobutton-box').first().click();
  await page.getByRole('textbox', { name: 'Net Profit last year*' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('.p-checkbox-box').click();
  await page.locator('div').filter({ hasText: 'Please confirm all the' }).nth(2).click();
  await page.locator('div').filter({ hasText: 'Please confirm all the' }).nth(2).click();
  await page.locator('div').filter({ hasText: 'Please confirm all the' }).nth(3).click();
  await page.locator('#checkbox').click();
  await page.locator('div').filter({ hasText: 'Please confirm all the' }).nth(2).click();
  await page.getByRole('button', { name: ' Previous' }).click();
  await page.getByRole('button', { name: ' Previous' }).click();
  await page.getByRole('textbox', { name: 'Time with Current Employer*' }).click();
  await page.getByRole('textbox', { name: 'Time with Current Employer*' }).fill('0');
  await page.locator('#pn_id_1031').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'Accountant' }).click();
  await page.locator('#pn_id_1034').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'Contractor' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('.p-checkbox-box').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  // post submission page
  await page.goto('https://testportaludc.aurionpro.com/dealer/standard-quote/edit/5263');
  await page.locator('.col-2.status').click();
  await page.getByText('Submit').click();
  await page.getByRole('button', { name: 'Next' }).click();
});