import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  //Login
  await page.goto('https://testportaludc.aurionpro.com/login');
  await page.getByRole('button', { name: 'Login with FIS' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).click();
  await page.getByRole('searchbox', { name: 'Username' }).fill('pramod.more');
  await page.getByRole('button', { name: 'Proceed' }).click();
  await page.getByRole('textbox', { name: 'Password' }).click();
  await page.getByRole('textbox', { name: 'Password' }).fill('Sanvi@123456');
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).click();
  await page.getByRole('textbox').nth(1).fill('7');
  await page.getByRole('textbox').nth(2).fill('0');
  await page.getByRole('textbox').nth(3).fill('7');
  await page.getByRole('textbox').nth(4).fill('4');
  await page.getByRole('textbox').nth(5).fill('1');
  await page.locator('input[type="text"]').nth(5).fill('5');
  await page.getByRole('radio', { name: 'Yes, this is my computer or' }).check();
  await page.getByRole('button', { name: 'Sign in' }).click();
  //Before Dashboard
  await page.getByRole('link', { name: 'Quotes & Applications Quotes' }).click();
  //Dashboard page
  await page.getByRole('button', { name: ' + Create Standard Quote' }).click();
  await page.getByRole('dialog').locator('div').filter({ hasText: 'Credit Sale Agreement Assured' }).click();
  await page.goto('https://testportaludc.aurionpro.com/dealer/standard-quote'); 
 //stand quote page
  await page.getByRole('link', { name: 'Credit Sale Agreement' }).click();
  await page.locator('#pn_id_166').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'CSA-B-Assigned' }).click();
  await page.locator('#pn_id_169').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByText('Webform - CSA Business - MV').click();
  await page.locator('text').filter({ hasText: 'Originator Reference' }).locator('#text').click();
  await page.locator('text').filter({ hasText: 'Originator Reference' }).locator('#text').fill('test');
  await page.locator('input[name="assetTypeDD"]').click();
  await page.getByRole('searchbox').click();
  await page.getByRole('searchbox').fill('car');
  await page.getByText('Car and Light Commercial /').click();
  await page.locator('#pn_id_183').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'New' }).click();
  await page.getByRole('button', { name: 'Asset, Insurance & Trade-in' }).click();
  await page.locator('.cursor-pointer.fa-pen-to-square').click();
  await page.getByRole('textbox', { name: 'Asset Value* Sum Insured Net' }).click();
  await page.getByRole('textbox', { name: 'Asset Value* Sum Insured Net' }).click();
  await page.getByRole('textbox', { name: 'Asset Value* Sum Insured Net' }).press('ArrowRight');
  await page.locator('text').filter({ hasText: 'Make' }).locator('#text').click();
  await page.locator('text').filter({ hasText: 'Make' }).locator('#text').click();
  await page.locator('text').filter({ hasText: 'Make' }).locator('#text').fill('a');
  await page.locator('text').filter({ hasText: 'Make' }).locator('#text').press('Tab');
  await page.locator('text').filter({ hasText: 'Model' }).locator('#text').fill('a');
  await page.locator('text').filter({ hasText: 'Model' }).locator('#text').press('Tab');
  await page.locator('text').filter({ hasText: 'Variant' }).locator('#text').fill('a');
  await page.locator('text').filter({ hasText: 'Variant' }).locator('#text').press('Tab');
  await page.locator('text').filter({ hasText: 'Rego No.' }).locator('#text').fill('a');
  await page.locator('text').filter({ hasText: 'Rego No.' }).locator('#text').press('Tab');
  await page.getByRole('button', { name: 'Submit' }).click();
  await page.getByRole('button', { name: 'Close' }).click();
  await page.locator('app-dealer-finance').getByRole('spinbutton').click();
  await page.locator('app-dealer-finance').getByRole('spinbutton').press('ArrowRight');
  await page.locator('date').filter({ hasText: 'First Payment' }).getByLabel('Choose Date').click();
  await page.getByText('10', { exact: true }).click();
  await page.getByRole('button', { name: 'Calculate' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.goto('https://testportaludc.aurionpro.com/dealer/standard-quote/create/5156');
  // Customer Page
  await page.getByRole('button', { name: ' Add Borrowers / Guarantors' }).click();
  await page.locator('p-radiobutton').filter({ hasText: 'Individual' }).click();
  await page.locator('text').filter({ hasText: 'First Name' }).locator('#text').click();
  await page.locator('text').filter({ hasText: 'First Name' }).locator('#text').fill('Test');
  await page.locator('text').filter({ hasText: 'Last Name' }).locator('#text').click();
  await page.locator('text').filter({ hasText: 'Last Name' }).locator('#text').fill('Demo');
  await page.getByRole('button', { name: 'Choose Date' }).click();
  await page.getByText('10', { exact: true }).click();
  await page.getByRole('button', { name: 'Search' }).click();
  await page.getByRole('button', { name: ' Add New Customer' }).click();
  //Business Individual
  await page.getByRole('textbox', { name: 'Trading Name* GST Number Time' }).click();
  await page.getByRole('textbox', { name: 'Trading Name* GST Number Time' }).fill('XYA Traders');
  await page.locator('text').filter({ hasText: 'GST Number' }).locator('#text').click();
  await page.locator('text').filter({ hasText: 'GST Number' }).locator('#text').fill('1234');
  await page.locator('#pn_id_568').getByRole('combobox').click();
  await page.getByText('Vegetable Growing').click();
  await page.locator('text').filter({ hasText: 'Time in Business' }).locator('#text').click();
  await page.locator('text').filter({ hasText: 'Time in Business' }).locator('#text').fill('1');
  await page.locator('text').filter({ hasText: 'Time in Business' }).locator('#text').press('Tab');
  await page.locator('#text').nth(3).fill('1');
  await page.locator('#pn_id_532').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'Mr', exact: true }).click();
  await page.locator('#pn_id_539').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'Male', exact: true }).click();
  await page.locator('#pn_id_543').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'Married', exact: true }).click();
  await page.locator('#pn_id_546 > .p-dropdown-trigger').click();
  await page.getByRole('option', { name: '0' }).click();
  await page.locator('#pn_id_548 > .p-dropdown-trigger').click();
  await page.getByText('+61').click();
  await page.getByRole('textbox', { name: 'Area code' }).click();
  await page.locator('#pn_id_548 > .p-dropdown-trigger').click();
  await page.getByRole('option', { name: '+61' }).click();
  await page.getByRole('textbox', { name: 'Area code' }).click();
  await page.locator('#pn_id_548 > .p-dropdown-trigger').click();
  await page.getByText('+61').click();
  await page.getByRole('textbox', { name: '+' }).click();
  await page.getByRole('textbox', { name: '+' }).press('Tab');
  await page.locator('.p-hidden-accessible').first().press('Tab');
  await page.getByRole('textbox', { name: 'Area code' }).click();
  await page.getByRole('textbox', { name: 'Area code' }).click();
  await page.getByRole('textbox', { name: 'Area code' }).fill('12');
  await page.getByRole('textbox', { name: 'Area code' }).press('Tab');
  await page.getByRole('textbox', { name: 'Phone number' }).fill('12345');
  await page.locator('#pn_id_548 > .p-dropdown-trigger').click();
  await page.getByText('+54').click();
  await page.locator('.col-5').click();
  await page.locator('.p-inputtext.p-component.p-element.ng-untouched.ng-pristine.ng-invalid').fill('wee@gmail.com');
  await page.locator('div').filter({ hasText: /^Add Other Number$/ }).click();
  await page.locator('#pn_id_551 > .p-dropdown-trigger').click();
  await page.getByRole('option', { name: 'None' }).click();
  await page.locator('#pn_id_557 > .p-dropdown-trigger').click();
  await page.getByRole('listbox', { name: 'Option List' }).click();
  await page.locator('#pn_id_557 > .p-dropdown-trigger').click();
  await page.getByRole('option', { name: 'Yes' }).click();
  await page.locator('#pn_id_559 > .p-dropdown-trigger').click();
  await page.getByLabel('Option List').getByText('New Zealand').click();
  await page.locator('#pn_id_561 > .p-dropdown-trigger').click();
  await page.getByRole('option', { name: 'New Zealand' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  //Address Details
  await page.locator('input[name="physicalSearchValue"]').click();
  await page.locator('input[name="physicalSearchValue"]').fill('auckl');
  await page.getByRole('option', { name: '1 Auckland Road, St Heliers,' }).click();
  await page.locator('#pn_id_587').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'Boarding' }).click();
  await page.getByRole('spinbutton').first().click();
  await page.getByRole('spinbutton').first().press('Tab');
  await page.locator('input[name="previousSearchValue"]').click();
  await page.locator('input[name="previousSearchValue"]').fill('auck');
  await page.getByText('2 Auckland Road, St Heliers,').click();
  await page.locator('input[name="postalSearchValue"]').click();
  await page.locator('p-radiobutton:nth-child(2) > .p-radiobutton > .p-radiobutton-box').click();
  await page.locator('input[name="postalSearchValue"]').click();
  await page.locator('input[name="postalSearchValue"]').fill('auckla');
  await page.getByText('3 Auckland Road, St Heliers,').click();
  await page.locator('input[name="registerSearchValue"]').click();
  await page.locator('input[name="registerSearchValue"]').fill('auckl');
  await page.getByText('5 Auckland Road, St Heliers,').click();
  await page.getByRole('button', { name: 'Next' }).click();
  //Employment Details
  await page.getByRole('textbox', { name: 'Employer Name*', exact: true }).click();
  await page.getByRole('textbox', { name: 'Employer Name*', exact: true }).fill('AVCC');
  await page.locator('#pn_id_711').getByRole('combobox').click();
  await page.getByRole('option', { name: 'Accountant' }).click();
  await page.locator('#pn_id_714').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByText('Full time employed').click();
  await page.getByRole('textbox', { name: 'Time with Current Employer' }).click();
  await page.getByRole('textbox', { name: 'Time with Current Employer' }).fill('0');
  await page.getByRole('textbox', { name: 'Time with Current Employer' }).press('Tab');
  await page.locator('#text').nth(1).fill('9');
  await page.locator('text').filter({ hasText: 'Employer Name' }).locator('#text').click();
  await page.locator('text').filter({ hasText: 'Employer Name' }).locator('#text').fill('ABFF');
  await page.locator('#pn_id_720').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.locator('#pn_id_720').getByRole('combobox').click();
  await page.locator('#pn_id_720').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.locator('#pn_id_723').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('combobox', { name: 'Accountant' }).click();
  await page.getByText('Employer Name Occupation * Occupation is required Employment Type * Employment').click();
  await page.locator('#pn_id_720').getByRole('combobox').click();
  await page.locator('#pn_id_720').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.locator('#pn_id_720').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.locator('#pn_id_720').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('textbox', { name: 'Time with Current Employer' }).click();
  await page.getByRole('textbox', { name: 'Time with Current Employer' }).fill('1');
  await page.locator('#pn_id_720').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.locator('#pn_id_720').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.locator('.p-fluid.px-2.ng-star-inserted.ng-invalid > div > div:nth-child(5)').click();
  await page.locator('text').filter({ hasText: 'Time with Previous Employer' }).locator('#text').click();
  await page.locator('text').filter({ hasText: 'Time with Previous Employer' }).locator('#text').fill('1');
  await page.locator('.p-element.ng-untouched > .p-field').click();
  await page.locator('text').filter({ hasText: 'Time with Previous Employer' }).locator('#text').fill('11');
  await page.locator('.p-fluid.px-2.ng-star-inserted.ng-invalid > div > div:nth-child(5)').click();
  await page.locator('.p-fluid.px-2.ng-star-inserted.ng-invalid > div > div:nth-child(7)').click();
  await page.locator('#text').nth(4).click();
  await page.locator('#text').nth(4).fill('1');
  await page.locator('#pn_id_720').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'No results found' }).click();
  await page.locator('#pn_id_720').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
  //Financial Position
  await page.locator('.p-radiobutton-box').first().click();
  await page.getByRole('textbox', { name: 'Net Profit last year*' }).click();
  await page.getByRole('textbox', { name: 'Net Profit last year*' }).click();
  await page.getByRole('textbox', { name: 'Net Profit last year*' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Net Profit last year*' }).press('ArrowLeft');
  await page.getByRole('textbox', { name: 'Net Profit last year*' }).press('ArrowLeft');
  await page.getByRole('button', { name: 'Next' }).click();
  
  await page.locator('.p-checkbox-box').click();
  await page.getByText('Address Details').click();
  await page.locator('input[name="physicalSearchValue"]').click();
  await page.locator('input[name="physicalSearchValue"]').fill('auckl');
  await page.getByText('1 Auckland Road, St Heliers,').click();
  await page.getByRole('spinbutton').nth(2).click();
  await page.getByRole('spinbutton').nth(2).click();
  await page.getByRole('spinbutton').nth(2).press('Tab');
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('#pn_id_896').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByRole('option', { name: 'Accountant' }).click();
  await page.locator('#pn_id_899').getByRole('button', { name: 'dropdown trigger' }).click();
  await page.getByText('Part time employed').click();
  await page.getByRole('button', { name: 'Next' }).click();
  await page.getByRole('button', { name: 'Next' }).click();
//Reference Details
  await page.locator('.p-checkbox-box').click();
  await page.getByRole('button', { name: 'Submit' }).click();
  // post sunmission
  await page.getByRole('button', { name: 'Next' }).click();
  await page.locator('input[name="workFlowStatus"]').click();
  await page.getByText('Submit').click();
  await page.getByRole('tab', { name: 'Documents' }).click();
  await page.locator('tr:nth-child(8) > td > .p-element.ng-untouched > .p-checkbox > .p-checkbox-box').click();
  await page.getByRole('button', { name: ' Download' }).click();
});